version: "3.8"
services:

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200

  boot-admin:
    image: slydeveloper/spring-boot-admin
    container_name: boot-admin
    ports:
      - "1111:1111"
    environment:
      - SPRING_BOOT_ADMIN_SECURITY_ENABLED=false

  tomcat:
    image: tomcat:9.0.37-jdk11-openjdk
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./setenv.sh:/usr/local/tomcat/bin/setenv.sh
      - ./elastic-apm.log:/usr/local/tomcat/elastic-apm.log
      - ./elastic-apm-agent-1.18.1.jar:/usr/local/tomcat/bin/elastic-apm-agent.jar
      - ./webapps:/usr/local/tomcat/webapps

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.8.0
    container_name: apm-server
    ports:
      - "8200:8200"
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
